{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virtusize.android",
    "module": "virtusize-auth",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.0.1.aar",
          "url": "virtusize-auth-1.0.1.aar",
          "size": 64448,
          "sha512": "8e67d23d764ff1dca9c700fce1c6944a5a6f2cf40dce7b2297711066573347ff8443e8ee01577129d1dbaaced853a98ea4660cb357bab194f5965982f204feb9",
          "sha256": "ab88852a87973e6cf1df17cefe64726cda9884ecd0d4587afab7182d538ce31a",
          "sha1": "7bacfb38866f4668fad4159c16bacb15f495966a",
          "md5": "58b2a3f64de2150f2328d915a3ceb913"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.0.1.aar",
          "url": "virtusize-auth-1.0.1.aar",
          "size": 64448,
          "sha512": "8e67d23d764ff1dca9c700fce1c6944a5a6f2cf40dce7b2297711066573347ff8443e8ee01577129d1dbaaced853a98ea4660cb357bab194f5965982f204feb9",
          "sha256": "ab88852a87973e6cf1df17cefe64726cda9884ecd0d4587afab7182d538ce31a",
          "sha1": "7bacfb38866f4668fad4159c16bacb15f495966a",
          "md5": "58b2a3f64de2150f2328d915a3ceb913"
        }
      ]
    }
  ]
}
