{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virtusize.android",
    "module": "virtusize-auth",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.0.2.aar",
          "url": "virtusize-auth-1.0.2.aar",
          "size": 64597,
          "sha512": "e6abdb94f23bf3b590c9c2bf7e8d6ff88dadc459a60e4ee2d4c97bf83ef2466c7c66bc5aabeb5858d7b39f459de972ac8de8a27296ff0beb188a351a4ee204c2",
          "sha256": "88a0149070a70e6b4eb662954355ef10aaccb19be7db3ea35a1275754676b0f1",
          "sha1": "86b744454fe78d825cf561fb57cbb757cf99b8ba",
          "md5": "91f72416de01823f27cae6bf7850becb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.virtusize.android",
          "module": "virtusize-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.0.2.aar",
          "url": "virtusize-auth-1.0.2.aar",
          "size": 64597,
          "sha512": "e6abdb94f23bf3b590c9c2bf7e8d6ff88dadc459a60e4ee2d4c97bf83ef2466c7c66bc5aabeb5858d7b39f459de972ac8de8a27296ff0beb188a351a4ee204c2",
          "sha256": "88a0149070a70e6b4eb662954355ef10aaccb19be7db3ea35a1275754676b0f1",
          "sha1": "86b744454fe78d825cf561fb57cbb757cf99b8ba",
          "md5": "91f72416de01823f27cae6bf7850becb"
        }
      ]
    }
  ]
}
