{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virtusize.android",
    "module": "virtusize-auth",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-0.0.2.aar",
          "url": "virtusize-auth-0.0.2.aar",
          "size": 55340,
          "sha512": "ed3289007d0c8ae9066ee29d137aeabd21521c9c23b7e929ab6cccc18510a21f57905065d02ad0a494c9dca2c794a779b539ad59029d16f330d08dbe35f09176",
          "sha256": "20eb9977db3a2b6eaecdf83c9dcff545b6ce0554e58fe59db13f2a7ed19d8a98",
          "sha1": "8bc2b1258a021dc1bd8537a3e687f674367bd4cf",
          "md5": "603bca6bedb0ef95e5caff38af7375a3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-0.0.2.aar",
          "url": "virtusize-auth-0.0.2.aar",
          "size": 55340,
          "sha512": "ed3289007d0c8ae9066ee29d137aeabd21521c9c23b7e929ab6cccc18510a21f57905065d02ad0a494c9dca2c794a779b539ad59029d16f330d08dbe35f09176",
          "sha256": "20eb9977db3a2b6eaecdf83c9dcff545b6ce0554e58fe59db13f2a7ed19d8a98",
          "sha1": "8bc2b1258a021dc1bd8537a3e687f674367bd4cf",
          "md5": "603bca6bedb0ef95e5caff38af7375a3"
        }
      ]
    }
  ]
}
