{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virtusize.android",
    "module": "virtusize-auth",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.0.3.aar",
          "url": "virtusize-auth-1.0.3.aar",
          "size": 65291,
          "sha512": "231e6b0c9c79a80267bfe48b0ccc13ec70d766ff702d946ebbfdeaf7f2cbac0ad423b9e54a4d36666c25a5c99ca1cddd6135fabab8e950f436250de6f3d56f83",
          "sha256": "ef89f43183278baec4f4316f343ee122f80b08715a67b397cf6b823e040fe0ab",
          "sha1": "21990290c86420a8f672f1fd53b6b453408e41f6",
          "md5": "7a86a866cf98add7d4278cd0595b32f6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.virtusize.android",
          "module": "virtusize-core",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.0.3.aar",
          "url": "virtusize-auth-1.0.3.aar",
          "size": 65291,
          "sha512": "231e6b0c9c79a80267bfe48b0ccc13ec70d766ff702d946ebbfdeaf7f2cbac0ad423b9e54a4d36666c25a5c99ca1cddd6135fabab8e950f436250de6f3d56f83",
          "sha256": "ef89f43183278baec4f4316f343ee122f80b08715a67b397cf6b823e040fe0ab",
          "sha1": "21990290c86420a8f672f1fd53b6b453408e41f6",
          "md5": "7a86a866cf98add7d4278cd0595b32f6"
        }
      ]
    }
  ]
}
