{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virtusize.android",
    "module": "virtusize-auth",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.1.1.aar",
          "url": "virtusize-auth-1.1.1.aar",
          "size": 48394,
          "sha512": "52a9fedc3b9cf3648ccb6d198db8645909841e15029a00ea2e806e6a8a3c4c2f5c76edd288a94dea3d4f28ea2ab4d84d9c7f48236c92587702ea83b6b0c79024",
          "sha256": "6d4eccba2d1113d6f695565467c41fcf8cf712d9e88ac76f71fa8e34c9138f45",
          "sha1": "316952549e8964d6008c0e73c9fc91907a4d3f52",
          "md5": "92294eee8dac509c7744f2f6a7320a09"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.virtusize.android",
          "module": "virtusize-core",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.1.1.aar",
          "url": "virtusize-auth-1.1.1.aar",
          "size": 48394,
          "sha512": "52a9fedc3b9cf3648ccb6d198db8645909841e15029a00ea2e806e6a8a3c4c2f5c76edd288a94dea3d4f28ea2ab4d84d9c7f48236c92587702ea83b6b0c79024",
          "sha256": "6d4eccba2d1113d6f695565467c41fcf8cf712d9e88ac76f71fa8e34c9138f45",
          "sha1": "316952549e8964d6008c0e73c9fc91907a4d3f52",
          "md5": "92294eee8dac509c7744f2f6a7320a09"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "virtusize-auth-1.1.1-sources.jar",
          "url": "virtusize-auth-1.1.1-sources.jar",
          "size": 33415,
          "sha512": "a25a3cff7d613ef2899e8095896429ff34d9e6d896c5b7cbb2280d360eaf5beed8a0b1661dabc2a9527509839274f17b1e73d65eb38e6c7f60132d646591ce09",
          "sha256": "4d06555402c37522a55a42bb13f695ea0f1248cf31edc17c4500b109c7fd5086",
          "sha1": "65c2195d408d169b597d00406be6dc4ad4e4e882",
          "md5": "75887b9816600d7bd796f2b1c1007192"
        }
      ]
    }
  ]
}
