{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virtusize.android",
    "module": "virtusize-auth",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.0.6.aar",
          "url": "virtusize-auth-1.0.6.aar",
          "size": 43428,
          "sha512": "5642dd2b6793f1355caef11dc699499c152740a26b0bbccec7aa54b62bc3738195e75ac221c6d71fc309b287bbe942207c6545aceeb8d802e421b69925774039",
          "sha256": "b257bca923dcece1d932444ec024eadcc225de50ec93e769be96b418e0fcdb77",
          "sha1": "b038903fd45407e375d8fe3f2b0d1d18f221e24a",
          "md5": "4e6b0334da1ffb00c4d0368c99a1ee72"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.virtusize.android",
          "module": "virtusize-core",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "virtusize-auth-1.0.6.aar",
          "url": "virtusize-auth-1.0.6.aar",
          "size": 43428,
          "sha512": "5642dd2b6793f1355caef11dc699499c152740a26b0bbccec7aa54b62bc3738195e75ac221c6d71fc309b287bbe942207c6545aceeb8d802e421b69925774039",
          "sha256": "b257bca923dcece1d932444ec024eadcc225de50ec93e769be96b418e0fcdb77",
          "sha1": "b038903fd45407e375d8fe3f2b0d1d18f221e24a",
          "md5": "4e6b0334da1ffb00c4d0368c99a1ee72"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "virtusize-auth-1.0.6-sources.jar",
          "url": "virtusize-auth-1.0.6-sources.jar",
          "size": 30553,
          "sha512": "e96e0f7f0d3c5efa9430ae158a0e487d74347427e4f1ebc6e99bb11493e2f9e95d01faba0c82bc8af440cb429bab72ab97e725ff1b86bbfa298a46c8272f16c0",
          "sha256": "75a163414d6583c57ef48ddfd747183d41b9f3842342cba8a90bf39873321a7c",
          "sha1": "443f425f7a59dbf761272d0b56de8c2552c755e1",
          "md5": "77a7f6668313c25e0e39dfc82d0d68ce"
        }
      ]
    }
  ]
}
